### ISSUE TITLE
Incorrect Ada code for enum and repeated string and exception for only enum

### ISSUE THREAD

**Issue by mgrojo** [reznikmm/protobuf#11]
Given this proto file:

```proto
syntax = "proto3";

package Test2;

enum Enum_T
{
  ENUM1 = 0;
  ENUM2 = 1;
}
message Repeated_String_T
{
  repeated string items = 1;
}
```

The generated code does not compile, due to missing `with PB_Support`:

```
test_2-test_2.ads:11:34: error: "PB_Support" is undefined
```

It's something funny, because if you remove the `Repeated_String_T` and leave only the enum, the generator has an exception:

```
raised CONSTRAINT_ERROR : compiler-file_descriptors.adb:179 access check failed
--ada_out: protoc-gen-ada: Plugin failed with status code 1.
```

**Comment by mgrojo** [comment]
This one is more subtle:

```
syntax = "proto3";

package Test3;

enum Optional_Thing
{
  Undefined = 0;
  Some_Value = 1;
  Other_Value = 2;
}

message Thing
{
   Optional_Thing thing = 1;
}
```

That generates an Ada package with two Optional_Thing types, the original from the proto file and one to allow not setting the message Thing. I won't use that Optional_ prefix as workaround, in fact, if everything is optional in proto3 there's no sense in calling something Optional. No idea how this could be treated properly to avoid these name clashes.

**Comment by reznikmm** [comment]
This should work also.

PS. Feel free to support me on [patreon](https://patreon.com/ada_ru) if you find this project useful.
