### ISSUE TITLE
Bintray is deprecated and the link to rpm is not working

### ISSUE THREAD

**Issue by mgrojo** [reznikmm/protobuf#3]
Bintray is deprecated and the link to rpm is not working now. I'd use the release page here in github to store the rpm as an artifact.

**Comment by reznikmm** [comment]
Thank you for the issue. I've moved rpm to [Fedora COPR](https://copr.fedorainfracloud.org/coprs/reznik/ada/). You should be able to download RPM from there.

I'll fix README
